apiVersion: v1
kind: Service
metadata:
  name: om-bkm2-bff-service
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: om-bkm2-bff