apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/huynhnhatduy108/demo-argo.git
    targetRevision: HEAD
    path: apps/app1
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
