apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: demo-applicationset  
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort