apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-bkm2-dsd-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: om-bkm2-dsd-ui
  template:
    metadata:
      labels:
        app: om-bkm2-dsd-ui
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
      # serviceAccount: om-bkm2-bff-service-account
      containers:
        - name: okm2-ui
          image: nginx:latest
          ports:
          - containerPort: 80
              name: container-port
          envFrom:
            - configMapRef:
                name: om-bkm2-dsd-ui-env-var
          env:
            - name: NEXT_PUBLIC_FIREBASE_SENDER_ID
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_SENDER_ID
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_FIREBASE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_API_KEY
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_FIREBASE_APP_ID
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_APP_ID
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_FIREBASE_DATABASE_ID
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_DATABASE_ID
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
                  name: om-bkm2-dsd-ui
            - name: NEXT_PUBLIC_LAUNCH_DARKLY_CLIENT_SIDE_ID
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_LAUNCH_DARKLY_CLIENT_SIDE_ID
                  name: launch-darkly