
apiVersion: v1
kind: Service
metadata:
  name: okm2-backend-svc
spec:
  selector:
    app: okm2-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: okm2-ui-svc
spec:
  selector:
    app: okm2-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80