# apiVersion: v1
# kind: Service
# metadata:
#   name: okm2-backend-svc
# spec:
#   selector:
#     app: okm2-backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#   type: ClusterIP


# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: okm2-frontend-svc
# spec:
#   selector:
#     app: okm2-frontend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: ClusterIP


apiVersion: v1
kind: Service
metadata:
  name: okm2-backend-svc
spec:
  selector:
    app: okm2-backend
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80   
      nodePort: 30081   
  type: NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: okm2-frontend-svc
spec:
  selector:
    app: okm2-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30082
  type: NodePort