# apiVersion: argoproj.io/v1alpha1
# kind: ApplicationSet
# metadata:
#   name: om-flm-infras-ingress-git-dev
# spec:
#   generators:
#     - git:
#         repoURL: https://github.com/ocean-network-express/om-flm-config.git
#         revision: HEAD
#         directories:
#           - path: infras/kustomize/flm/k8s/overlays/dev
#   template:
#     metadata:
#       name: om-flm-infas-ingress-{{path.basename}}
#     spec:
#       project: om-flm
#       source:
#         repoURL: https://github.com/ocean-network-express/om-flm-config.git
#         targetRevision: HEAD
#         path: "{{path}}"
#       destination:
#         server: https://34.87.70.201
#         namespace: flm-dev
#       syncPolicy:
#         automated: { prune: true }
