apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ./hpa.yaml

patches:
# - path: ./replicas.yaml


configMapGenerator:
- name: mykustom-map
  env: config.properties