apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: om-bkm2-ui-prod
spec:
  generators:
    - git:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        revision: HEAD
        directories:
          - path: apps/om-bkm2-ui/k8s/overlays/prod
  template:
    metadata:
      name: om-bkm2-ui-prod
    spec:
      project: om-bkm2
      source:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: bkm2-prod
      syncPolicy:
        automated: { prune: true }
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: om-bkm2-backend-prod
spec:
  generators:
    - git:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        revision: HEAD
        directories:
          - path: apps/om-bkm2-backend/k8s/overlays/prod
  template:
    metadata:
      name: om-bkm2-backend-prod
    spec:
      project: om-bkm2
      source:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: bkm2-prod
      syncPolicy:
        automated: { prune: true }
