apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: om-bkm2-ui-dev
spec:
  generators:
    - git:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        revision: HEAD
        files:
          - path: apps/om-bkm2-ui/k8s/overlays/dev/kustomization.yaml
  template:
    metadata:
      # sẽ thành om-bkm2-ui-kustomization
      name: om-bkm2-ui-{{files.basename}}
    spec:
      project: om-bkm2
      source:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        targetRevision: HEAD
        path: "{{files.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: bkm2-dev
      syncPolicy:
        automated:
          prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: om-bkm2-backend-dev
spec:
  generators:
    - git:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        revision: HEAD
        directories:
          - path: apps/om-bkm2-backend/k8s/overlays/dev
  template:
    metadata:
      name: om-bkm2-backend-dev
    spec:
      project: om-bkm2
      source:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        # namespace: bkm2-dev
      syncPolicy:
        automated: { prune: true }
