apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: om-bkm2-ui-dev
  namespace: argocd               # namespace ArgoCD của bạn
spec:
  project: om-bkm2
  source:
    repoURL: https://github.com/huynhnhatduy108/demo-argo.git
    targetRevision: HEAD
    path: apps/om-bkm2-ui/k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: bkm2-dev
  syncPolicy:
    automated:
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: om-bkm2-backend-dev
spec:
  generators:
    - git:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        revision: HEAD
        directories:
          - path: apps/om-bkm2-backend/k8s/overlays/dev
  template:
    metadata:
      name: om-bkm2-backend-dev
    spec:
      project: om-bkm2
      source:
        repoURL: https://github.com/huynhnhatduy108/demo-argo.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        # namespace: bkm2-dev
      syncPolicy:
        automated: { prune: true }
