apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# - path: ./replicas.yaml


configMapGenerator:
- envs:
  - config.properties
  name: mykustom-map
images:
- name: nginx
  newName: juanje/angular-template
  newTag: latest
