apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: om-bkm2-ui-service-account@one-global-chorus-bkm2-prod.iam.gserviceaccount.com
  name: om-bkm2-ui-service-account