kind: ConfigMap
apiVersion: v1
metadata:
  name: om-bkm2-bff-configmap
data:
  APP_PORT: "5000"
  ENABLE_PLAYGROUND: "true"
  GRPC_HOST_VESSEL: "om-bkm2-vessel-management-service-svc.bkm2-dev.svc.cluster.local:9000"
  GRPC_HOST_SETTING: "om-bkm2-setting-service-svc.bkm2-dev.svc.cluster.local:9001"
  GRPC_HOST_POST_FIXTURE: "om-bkm2-post-fixture-service-svc.bkm2-dev.svc.cluster.local:9002"
  GCP_BUCKET_ID: "sea1-dev-chorus-bkm2-storage"
  GCP_SIGN_URL_EXPIRED_TIME: "1500000"
  GRAPHQL_UPLOAD_MAX_FILES: "1"
  GRAPHQL_UPLOAD_MAX_SIZE: "25"
  VESSEL_TEMPLATE_FILENAME: "Import_vessel_template.xlsx"
  GOOGLE_BUCKET_TEMPLATE_LOCATION: "templates"
  MDM_GRPC_HOST: "mdm-hub-dev-wpsqj2n4yq-as.a.run.app"
  ALLOW_DOMAINS: "https://localhost:3000,https://chorus-dev.one-line.com"
  BASE_URL_OPA_API: "http://localhost:8181/v1"

# LaunchDarkly
  LAUNCHDARKLY_bkm2_VESSEL_SPEC: "bkm2-vessel-specification"
  LAUNCHDARKLY_bkm2_DOCUMENT: "bkm2-vessel-document"
  LAUNCHDARKLY_bkm2_FLEET_LIST: "bkm2-one-fleet-list"
  LAUNCHDARKLY_bkm2_3767: "bkm2-3767"